[package]
name = "wadatsumi"
version = "0.1.0"
authors = ["Ryan Leckey <ryan@launchbadge.com>"]
edition = "2018"

[dependencies]
bitintr = "0.2.0"
num-derive = "0.2.4"
num-traits = "0.2.6"
unchecked_unwrap = "1.0.1"
derive_more = "0.14.0"
failure = "0.1"
byteorder = "1.3.1"
