[workspace]
members = [".", "crates/cpu-2a03", "crates/ppu-2c02", "crates/system-nes", "crates/system"]

[workspace.dependencies]
anyhow = "1.0.102"
bytes = "1.11.1"
clap = { version = "4.6.1", features = ["derive"] }
datatest-stable = "0.3.3"
divan = "0.1"
enum_dispatch = "0.3.13"
libtest-mimic = "0.8.2"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
wadatsumi-cpu-2a03 = { path = "crates/cpu-2a03" }
wadatsumi-ppu-2c02 = { path = "crates/ppu-2c02" }
wadatsumi-system = { path = "crates/system" }
wadatsumi-system-nes = { path = "crates/system-nes" }

[workspace.lints.rust]
unused = { level = "allow", priority = -1 }
missing_docs = { level = "warn", priority = -2 }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
inline_always = { level = "allow" }

[lints]
workspace = true

[package]
name = "wadatsumi"
version = "0.0.1"
edition = "2024"
license = "AGPL-3.0-or-later"

[dependencies]
anyhow.workspace = true
clap.workspace = true
tracing-subscriber.workspace = true
wadatsumi-system.workspace = true
wadatsumi-system-nes.workspace = true

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "debuginfo"
