[package]
name = "wadatsumi"
version = "0.0.0"
authors = [
  "Ryan Leckey <leckey.ryan@gmail.com>"
]

[dependencies]
sdl2 = "0.27.x"
strfmt = "0.1.x"
bitflags = "0.7"
log = "0.3.x"
env_logger = "0.3.x"
clap = "2.x"

[profile.release]
lto = true
opt-level = 3
debug = false
codegen-units = 1
debug-assertions = false
rpath = false
