[package]
name = "wadatsumi-cpu-2a03"
version = "0.0.1"
workspace = "../.."
edition = "2024"
license = "AGPL-3.0-or-later"

[dependencies]
tracing.workspace = true

[dev-dependencies]
anyhow.workspace = true
libtest-mimic.workspace = true
serde.workspace = true
serde_json.workspace = true

[[test]]
name = "single-step"
harness = false
